"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(i(u%wgfb=jvpb--6!kz=5#1fz%)vy-v05rd5t1msj2gc2ejy$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'inventory',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

JAZZMIN_SETTINGS = {
    "site_title": "Inventory Management Admin",
    "site_header": "Inventory Management Dashboard",
    "site_brand": "Inventory Management",
    "welcome_sign": "Welcome to the Inventory Management Admin Portal",
    "copyright": "PCPS, Patan College For Professional Studies",
    "order_with_respect_to": ["inventory", "accounts"],
    "icons": {
        "inventory.category": "fas fa-tags",
        "inventory.product": "fas fa-box",
        "inventory.supplier": "fas fa-truck",
        "inventory.customer": "fas fa-user",
        "inventory.order": "fas fa-shopping-cart",
        "inventory.orderitem": "fas fa-list",
    },
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "custom_links": {
        "inventory": [
            {
                "name": "API Docs (Swagger)",
                "url": "/swagger/",
                "icon": "fas fa-book",
                "permissions": ["auth.view_user"]
            },
            {
                "name": "API Docs (Redoc)",
                "url": "/redoc/",
                "icon": "fas fa-book-open",
                "permissions": ["auth.view_user"]
            },
        ]
    },
    "related_modal_active": True,
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "topmenu_links": [
        {"name": "Home", "url": "/admin/", "permissions": ["auth.view_user"]},
    ],
    "custom_dashboard": [
        {
            "app": "inventory",
            "model": "Product",
            "title": "Total Products",
            "icon": "fas fa-box",
            "description": "Total number of products in inventory.",
            "color": "primary"
        },
        {
            "app": "inventory",
            "model": "Category",
            "title": "Total Categories",
            "icon": "fas fa-tags",
            "description": "Total number of product categories.",
            "color": "info"
        },
        {
            "app": "inventory",
            "model": "Supplier",
            "title": "Total Suppliers",
            "icon": "fas fa-truck",
            "description": "Total number of suppliers.",
            "color": "success"
        },
        {
            "app": "inventory",
            "model": "Customer",
            "title": "Total Customers",
            "icon": "fas fa-user",
            "description": "Total number of customers.",
            "color": "warning"
        },
        {
            "app": "inventory",
            "model": "Order",
            "title": "Total Orders",
            "icon": "fas fa-shopping-cart",
            "description": "Total number of orders (sales & purchases).",
            "color": "danger"
        },
    ],
    "custom_welcome": "<h3>Welcome to the Inventory Management Dashboard</h3><p>Use the sidebar to manage products, categories, suppliers, customers, and orders. Use the analytics cards below for a quick overview of your inventory system.</p>",
}
